# Generated by Django 5.0.6 on 2024-06-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='data_criacao',
        ),
    ]
