# Generated by Django 5.0.6 on 2024-06-07 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_remove_filme_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
